#!/bin/bash -ex
# uid/gid 5000 testload
sudo groupadd --gid 5000 testload
sudo useradd --comment "Test Load User" --home-dir /home/testload \
    --gid 5000 --uid 5000 --shell /bin/true --groups ftp,video,tape testload
sudo chage --lastday 2001-01-01 --expiredate 2100-01-01 --inactive 50 \
    --mindays 10 --maxdays 2000 --warndays 14 testload

# uid/gid 5001 testsave1 (generated by test_save)
# uid/gid 5002 testsave2
sudo groupadd --gid 5002 testsave2
sudo useradd --comment "Test User 5002" --home-dir /home/testsave2 \
    --gid 5002 --uid 5002 --shell /bin/true --groups ftp,video,tape testsave2
sudo chage --lastday 2001-01-01 --expiredate 2100-01-01 --inactive 50 \
    --mindays 10 --maxdays 2000 --warndays 14 testsave2


# uid/gid 6001 testscan1 (generated by test_scan)
# uid/gid 6002 testscan2
sudo groupadd --gid 6002 testscan2
sudo useradd --comment "Test User 6002" --home-dir /home/testscan2 \
    --gid 6002 --uid 6002 --shell /bin/true --groups ftp,video,tape testscan2
sudo chage --lastday 2001-01-01 --expiredate 2100-01-01 --inactive 50 \
    --mindays 10 --maxdays 2000 --warndays 14 testsave2

#sudo useradd --comment "Test User 5003" --home-dir /home/testuser5003 \
#    --gid 5003 --uid 5003 --shell /bin/true --groups ftp,video,tape testuser5003
#sudo chage --lastday 2001-01-01 --expiredate 2100-01-01 --inactive 50 \
#    --mindays 10 --maxdays 2000 --warndays 14 testuser5003
sudo --preserve-env $VIRTUAL_ENV/bin/nosetests --with-coverage \
    --cover-package dynamodbusermanager --nocapture --process-timeout 10 \
    tests

cp .coverage /export
